### ISSUE TITLE
Internal Server Error ,ArgumentNullException: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-storefront#596]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version:  Chrome 98.0.4758.102
- Platform version: 3.204.0
- Storefront version: latest dev 2022-03-03

### Expected behavior
can use vue-starter-theme successfully.

### Steps to reproduce
1.Platform 3.204 is run successful.
2.Experience API version is 3.203.0
3.Profile Experience API version is 3.201.0
4.clone the latest storefront dev version,and clonse the latest version of vue-starter-theme
5.when input the command `dotnet run` ,some errors happend.

```
ArgumentNullException: Value cannot be null. (Parameter 'source')
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
System.Linq.Enumerable.Select<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, TResult> selector)
VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__5_0(MemoryCacheEntryOptions cacheEntry) in StoreService.cs
+
                return await Task.WhenAll(storeDtos.Select(x => ConvertStoreAndLoadDependeciesAsync(x)));
VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync<TItem>(IMemoryCache cache, string key, Func<MemoryCacheEntryOptions, Task<TItem>> factory, bool cacheNullValue) in MemoryCacheExtensions.cs
+
                        result = await factory(options);
VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in StoreService.cs
+
            return await _memoryCache.GetOrCreateExclusiveAsync(cacheKey, async (cacheEntry) =>
VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, string defaultStoreId) in StoreWorkContextBuilderExtensions.cs
+
            var stores = await storeService.GetAllStoresAsync();
VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in WorkContextBuildMiddleware.cs
+
            await builder.WithStoresAsync(_options.DefaultStore);
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Show raw exception details
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__5_0(MemoryCacheEntryOptions cacheEntry) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 44
   at VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync[TItem](IMemoryCache cache, String key, Func`2 factory, Boolean cacheNullValue) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront.Model\Common\Caching\MemoryCacheExtensions.cs:line 21
   at VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 38
   at VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, String defaultStoreId) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Domain\Stores\StoreWorkContextBuilderExtensions.cs:line 54
   at VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in E:\VirtoCommerce\5.Source\vc-storefront-dev\VirtoCommerce.Storefront\Middleware\WorkContextBuildMiddleware.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

![image](https://user-images.githubusercontent.com/5348170/156617011-0adba6e0-8b20-4885-935a-651ffdd008c5.png)

**Comment by six006** [comment]
I found the problem.
If the Password set error,it can't get the store information.

```
"Endpoint": {
      "Url": "http://localhost:10645/",
      "UserName": "admin",
      "Password": "store",
    },
```
